pyjobs/core/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap

from pyjobs.core.models import Job
from pyjobs.core.views import *


class PyJobsSitemap(Sitemap):
    changefreq = "always"
    priority = 0.5

    def items(self):
        return Job.get_publicly_available_jobs()

    def lastmod(self, obj):
        return obj.created_at


urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^job/(?P<pk>\d+)/$", job_view, name="job_view"),
    url(r"^summary/$", summary_view, name="job_view"),
    url(r"^services/$", services_view, name="services"),
    url(r"^contact/$", contact, name="contact"),
    url(r"^register/new/job/$", register_new_job, name="register_new_job"),
    url(r"^pythonistas/$", pythonistas_area, name="pythonistas_area"),
    url(r"^pythonistas/signup/$", pythonistas_signup, name="pythonistas_signup"),
    url(r"^password/$", pythonista_change_password, name="change_password"),
    url(r"^info/$", pythonista_change_info, name="change_info"),
    url(r"^applied-to/$", pythonista_applied_info, name="applied_to_info"),
    url(r"^jooble/$", jooble_feed, name="jooble_feed"),
    url(r"^job/(?P<pk>\d+)/rec/$", get_job_related_users, name="get_job_related_users"),
    url(r"^job/create/$", job_creation, name="job_creation"),
    url(r"^robots.txt$", robots_view, name="robots"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": {"jobs": PyJobsSitemap()}},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^select2/", include("django_select2.urls")),
    url(r"^feed/$", JobsFeed()),
    url(r"^feed/premium/$", PremiumJobsFeed()),
]

pyjobs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^admin_v2/", admin.site.urls),
    url("api/", include("pyjobs.api.urls", namespace="api")),
    url(r"", include("pyjobs.core.urls")),
    url(r"^login/$", auth_views.login, {"template_name": "login.html"}, name="login"),
    url(r"^logout/$", auth_views.logout, {"next_page": "/"}, name="logout"),
    url(
        r"^password_reset/$",
        auth_views.password_reset,
        {"template_name": "pythonistas-area-password-change.html"},
        name="password_reset",
    ),
    url(
        r"^password_reset/done/$",
        auth_views.password_reset_done,
        name="password_reset_done",
    ),
    url(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.password_reset_confirm,
        name="password_reset_confirm",
    ),
    url(
        r"^reset/done/$",
        auth_views.password_reset_complete,
        name="password_reset_complete",
    ),
]

pyjobs/core/models.py
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from raven.contrib.django.raven_compat.models import client

from datetime import timedelta

from pyjobs.core.email_utils import (
    contact_email,
    contato_cadastrado_empresa,
    contato_cadastrado_pessoa,
    vaga_publicada,
)
from pyjobs.core.managers import PublicQuerySet, ProfilingQuerySet
from pyjobs.core.newsletter import subscribe_user_to_chimp
from pyjobs.core.utils import post_telegram_channel


class Messages(models.Model):
    message_title = models.CharField(
        "Título da Mensagem", max_length=100, default="", blank=False
    )

    message_type = models.CharField(
        "Ticker usado no backend para ID da msg",
        default="offer",
        max_length=200,
        blank=False,
    )

    message_content = models.TextField("Texto do E-mail", default="")

    class Meta:
        verbose_name = "Mensagem"
        verbose_name_plural = "Mensagens"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    github = models.URLField(verbose_name="GitHub", blank=True, default="")
    linkedin = models.URLField(verbose_name="LinkedIn", blank=True, default="")
    portfolio = models.URLField(verbose_name="Portfolio", blank=True, default="")
    cellphone = models.CharField(
        verbose_name="Telefone",
        max_length=16,
        validators=[
            RegexValidator(
                regex="^((?:\([1-9]{2}\)|\([1-9]{2}\) |[1-9]{2}|[1-9]{2} )(?:[2-8]|9[1-9])[0-9]{3}(?:\-[0-9]{4}| [0-9]{4}|[0-9]{4}))$",
                message="Telefone inválido! Digite entre 11 e 15 caracteres que podem conter números, espaços, parênteses e hífen.",
            )
        ],
    )

    created_at = models.DateTimeField(auto_now_add=True)
    skills = models.ManyToManyField("Skill")

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    def __repr__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    class Meta:
        verbose_name = "Perfil"
        verbose_name_plural = "Perfis"
        ordering = ["-created_at"]

    objects = models.Manager.from_queryset(ProfilingQuerySet)()

    def profile_skill_grade(self, job):
        skills = self.skills.values_list("pk", flat=True)
        job_skills = Job.objects.get(pk=job).skills.values_list("pk", flat=True)
        return Profile.objects.grade(skills, job_skills)


STATE_CHOICES = [
    (0, "Acre"),
    (1, "Alagoas"),
    (2, "Amapá"),
    (3, "Amazonas"),
    (4, "Bahia"),
    (5, "Ceará"),
    (6, "Distrito Federal"),
    (7, "Espírito Santo"),
    (8, "Goiás"),
    (9, "Maranhão"),
    (10, "Mato Grosso"),
    (11, "Mato Grosso do Sul"),
    (12, "Minas Gerais"),
    (13, "Pará"),
    (14, "Paraíba"),
    (15, "Paraná"),
    (16, "Pernambuco"),
    (17, "Piauí"),
    (18, "Rio de Janeiro"),
    (19, "Rio Grande do Norte"),
    (20, "Rio Grande do Sul"),
    (21, "Rondônia"),
    (22, "Roraima"),
    (23, "Santa Catarina"),
    (24, "São Paulo"),
    (25, "Sergipe"),
    (26, "Tocantins"),
    (27, "Indeterminado"),
]

SALARY_RANGES = [
    (1, "R$ 0,00 a R$ 1.000,00"),
    (2, "R$ 1.000,01 a R$ 3.000,00"),
    (3, "R$ 3.000,01 a R$ 6.000,00"),
    (4, "R$ 6.000,01 a R$ 10.000,00"),
    (5, "R$ 10.000,01 ou mais"),
    (6, "A combinar"),
]

JOB_LEVELS = [
    (1, "Estágio"),
    (2, "Junior"),
    (3, "Pleno"),
    (4, "Sênior"),
    (5, "Indeterminado"),
]


class Job(models.Model):
    title = models.CharField(
        "Título da Vaga",
        max_length=100,
        default="",
        blank=False,
        help_text="Ex.: Desenvolvedor",
    )
    workplace = models.CharField(
        "Local",
        max_length=100,
        default="",
        blank=False,
        help_text="Ex.: Santana - São Paulo",
    )
    company_name = models.CharField(
        "Nome da Empresa",
        max_length=100,
        default="",
        blank=False,
        help_text="Ex.: ACME Inc",
    )
    application_link = models.URLField(
        verbose_name="Link para a Vaga",
        blank=True,
        default="",
        help_text="Ex.: http://goo.gl/hahaha",
    )
    company_email = models.EmailField(
        verbose_name="Email da Empresa", blank=False, help_text="Ex.: abc@def.com"
    )
    description = models.TextField(
        "Descrição da vaga",
        default="",
        help_text="Descreva um pouco da sua empresa e da vaga, tente ser breve",
    )
    requirements = models.TextField(
        "Requisitos da vaga",
        default="",
        help_text="Descreva os requisitos da sua empresa em bullet points\n\n-Usar Git\n-Saber Java",
    )
    premium = models.BooleanField("Premium?", default=False)
    public = models.BooleanField("Público?", default=True)
    ad_interested = models.BooleanField("Impulsionar*", default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    skills = models.ManyToManyField("Skill")

    # Filtering parts of the model

    ## This will allow users to filter on the homepage for jobs that respect their
    ## values, necessities or expectations

    state = models.IntegerField("Estado", choices=STATE_CHOICES, default=27)
    salary_range = models.IntegerField(
        "Faixa Salarial", choices=SALARY_RANGES, default=6
    )
    job_level = models.IntegerField(
        "Nível do Profissional", choices=JOB_LEVELS, default=5
    )
    remote = models.BooleanField("Esta vaga é remota?", default=False)

    objects = models.Manager.from_queryset(PublicQuerySet)()

    class Meta:
        ordering = ("-created_at",)
        indexes = [models.Index(fields=["created_at"])]

    def __str__(self):
        return self.title

    def get_application_link(self):
        return self.application_link if self.application_link != "" else False

    def get_premium_jobs():
        return Job.objects.premium().created_in_the_last(30)[:7]

    def get_publicly_available_jobs(term=None):
        return Job.objects.not_premium().created_in_the_last(30).search(term)

    def get_feed_jobs():
        return Job.objects.not_premium().created_in_the_last(7)

    def get_excerpt(self):
        return self.description[:500]

    def applied(self, request_user):
        return JobApplication.objects.filter(job=self, user=request_user).exists()

    def apply(self, request_user):
        JobApplication.objects.create(job=self, user=request_user)
        return True

    def get_weekly_summary(self):
        return Job.objects.created_in_the_last(7)

    def get_absolute_url(self):
        return "/job/{}".format(self.pk)

    def get_jobs_to_get_feedback(self):
        return Job.objects.created_days_ago(14)

    def get_expiration_date(self):
        return self.created_at + timedelta(days=30)


class JobApplication(models.Model):
    user = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    job = models.ForeignKey(Job, default="", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "job")
        verbose_name = "Job Application"
        verbose_name_plural = "Job Applications"

    def __str__(self):
        return "{} applied to {}".format(self.user, self.job)


class Contact(models.Model):
    name = models.CharField("Nome", max_length=100, default="", blank=False)
    subject = models.CharField("Assunto", max_length=100, default="", blank=False)
    email = models.EmailField("Email", default="", blank=False)
    message = models.TextField("Mensagem", default="", blank=False)


class Skill(models.Model):
    name = models.CharField("Skill", max_length=100, default="", blank=False)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


@receiver(post_save, sender=Profile)
def add_user_to_mailchimp(sender, instance, created, **kwargs):
    subscribe_user_to_chimp(instance)


@receiver(post_save, sender=JobApplication)
def send_email_notifing_job_application(sender, instance, created, **kwargs):
    msg_email_person = contato_cadastrado_pessoa(
        pessoa=instance.user, vaga=instance.job
    )
    msg_email_company = contato_cadastrado_empresa(
        pessoa=instance.user, vaga=instance.job
    )

    send_mail(
        "Parabéns! Você se inscreveu na vaga!",
        msg_email_person,
        "pyjobs@pyjobs.com.br",
        [instance.user.email],
    )
    send_mail(
        "Você possui mais um candidato para a sua vaga",
        msg_email_company,
        "pyjobs@pyjobs.com.br",
        [instance.job.company_email],
    )


def send_offer_email_template(job):
    message = Messages.objects.filter(message_type="offer")[0]
    message_text = message.message_content.format(company=job.company_name)
    message_title = message.message_title.format(title=job.title)
    send_mail(
        message_title,
        message_text,
        "vinicius@pyjobs.com.br",
        [job.company_email, "viniciuscarqueijo@gmail.com"],
    )


def send_feedback_collection_email(job):
    message = Messages.objects.filter(message_type="feedback")[0]
    message_text = message.message_content.format(company=job.company_name)
    message_title = message.message_title.format(title=job.title)
    send_mail(
        message_title,
        message_text,
        "vinicius@pyjobs.com.br",
        [job.company_email, "viniciuscarqueijo@gmail.com"],
    )


@receiver(post_save, sender=Job)
def new_job_was_created(sender, instance, created, **kwargs):
    if created:
        job = instance.title
        empresa = instance.company_name
        local = instance.workplace
        link = instance.pk
        message_text = "Nova oportunidade! {} - {} em {}\n http://www.pyjobs.com.br/job/{}/".format(
            job, empresa, local, link
        )

pyjobs/core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django_select2.forms import Select2MultipleWidget, Select2Widget

from pyjobs.core.models import Contact, Job, Profile, Skill


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            "title",
            "job_level",
            "company_name",
            "workplace",
            "remote",
            "state",
            "application_link",
            "company_email",
            "salary_range",
            "description",
            "requirements",
            "skills",
            "ad_interested",
        ]
        widgets = {"skills": Select2MultipleWidget}

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.widget.attrs.update({"placeholder": field.label})

        for key, field in self.fields.items():
            if key in ["state", "salary_range", "job_level"]:
                field.choices = field.choices[:-1]


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "subject", "email", "message"]


class RegisterForm(UserCreationForm):
    github = forms.URLField(
        widget=forms.TextInput(
            attrs={"placeholder": "Preencha com o link do seu GitHub (não obrigatório)"}
        ),
        required=False,
    )

    linkedin = forms.URLField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Preencha com o link do seu Linkedin (não obrigatório)"
            }
        ),
        required=False,
    )

    portfolio = forms.URLField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Preencha com o link do seu portfolio (não obrigatório)"
            }
        ),
        required=False,
    )

    cellphone = forms.CharField(
        label="Celular",
        widget=forms.TextInput(attrs={"placeholder": "Preencha com o seu telefone"}),
        required=True,
    )

    skills_ = forms.ModelMultipleChoiceField(
        label="Skills", queryset=Skill.objects.all(), widget=Select2MultipleWidget
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username")

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ["password1", "password2"]:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        instance = super(RegisterForm, self).save(commit=False)
        if commit:
            instance.save()

            profile = Profile(
                user=instance,
                github=self.cleaned_data["github"],
                linkedin=self.cleaned_data["linkedin"],
                portfolio=self.cleaned_data["portfolio"],
                cellphone=self.cleaned_data["cellphone"],
            )
            authenticate(
                username=instance.username, password=self.cleaned_data.get("password1")
            )
            profile.save()
            profile.skills = self.cleaned_data["skills_"]
            profile.save()
        return instance


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("github", "linkedin", "portfolio", "cellphone", "skills")
        widgets = {"skills": Select2MultipleWidget}

pyjobs/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{%block title%} PyJobs - A Central de Jobs Python
{%endblock%}
{%block main%}
    <main class="page landing-page">
        <section class="clean-block clean-hero" style="background-image:url(&quot;http://mediad.publicbroadcasting.net/p/shared/npr/styles/x_large/nprshared/201310/208254350.jpg&quot;);color:rgba(9, 162, 255, 0.90);">
            <div class="text">
                <h2>Procurando o melhor desenvolvedor Python para sua empresa?</h2>
                <p>Cadastre agora uma vaga e tenha acesso aos melhores profissionais do Brasil!</p>
                <a href="{% url 'job_creation' %}">
                    <button class="btn btn-lg btn-chamada" type="button">Cadastre uma vaga AGORA!</button>
                </a>
              </div>
        </section>
        <section class="clean-block clean-info dark" style="padding-bottom:25px;">
            <div class="container">
                <div class="block-heading" style="margin-top:-40px;">
                    <h2 class="text-info">Depoimentos</h2>
                    <hr>
                </div>
                <div class="row">
                  <div class="col-md-3" style="text-align:center;">
                      <img src="{%static 'assets/img/avatars/retake.jpg'%}" alt="" width="125" height="150">
                  </div>
                  <div class="col-md-9" style="text-align:center;">
                        <h3>O PyJobs &eacute; um recurso inestim&aacute;vel para o nosso recrutamento. Sempre encontramos os melhores talentos aqui.</h3>
                        <p><b>Rommel Andriotti - Retake</b></p>
                  </div>
                </div>
            </div>
        </section>
        <section class="clean-block features">
            <div class="container">
                <div id="oportunidades" class="block-heading">
                    <h2 class="text-info">Conheça as melhores oportunidades Python</h2>
                    <p>Todas as oportunidades listadas no PyJobs passaram por um processo de curadoria para garantir a melhor qualidade o possível ao desenvolvedor</p>
                </div>
                <div class="row justify-content-center" style="margin-top:10px;">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="color:#777;">Tenha sua vaga destacada aqui!</h4>
                                <h6 class="text-muted card-subtitle mb-2">Saiba como ter a sua vaga no topo e tenha sua empresa em destaque</h6>
                                <p class="card-text"  style="color:#777;">Encontre os melhores profissionais Python e tenha mais destaque na comunidade com a vaga destacada. Ela lhe proporcionará maior visibilidade e maior chance de contratação!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-3 d-none d-md-block"><a href="{% url 'contact' %}"><button class="btn btn-primary" type="button" style="height:75px;width:100%;margin-top:25px;">Entre em contato</button></a></div>
                </div>
                {% if premium_available_jobs %}
                {% for job in premium_available_jobs %}
                <div class="row justify-content-center" style="margin-top:10px;">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                              <a href="/job/{{job.pk}}">
                                <h4 class="card-title" style="font-weight: bold;">[Destaque] {{job.title}}</h4>
                              </a>
                                <h6 class="text-muted card-subtitle mb-2">Localização: {{job.workplace}}</h6>
                                <h6 class="text-muted card-subtitle mb-2">Postada: {{job.created_at|naturalday}}</h6>
                                <hr/>
                                {%for skill in job.skills.all%}
                                    <span class="badge badge-pill badge-primary">{{skill}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-3 d-none d-md-block"><a href="{% url 'job_view' job.pk %}"><button class="btn btn-primary" type="button" style="height:75px;width:100%;margin-top:25px;background-color:#ffe01b;color:#000;border: 0px solid #000;">Se Inscreva AGORA!</button></a></div>
                </div>
                {%endfor%}
                {% endif %}
                <div></div>
                <br>
                <hr>
                <div class="row justify-content-center" style="margin-top:10px;">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title" style="color:#777;">
                                    <i class="icon-magnifier icons"></i>&nbsp;&nbsp;Pesquisar vagas:
                                </h4>
                                <p class="card-text"  style="color:#777;">
                                    Use a pesquisa para procurar vagas na cidade que deseja, com o título, descrição ou requisitos.
                                    Ex: São Paulo, Data Scientist
                                </p>
                                    <form class="" method="get">
                                        <div class="row justify-content-center" style="margin-top:10px;">

                                        {% for field in filter.form.visible_fields %}
                                            <div class="form-group col-sm-4 col-md-4">
                                                {{field.label_tag}}
                                                {%render_field field class="form-control"%}
                                            </div>
                                        {% endfor %}
                                        </div>
                                        <button type="submit" class="btn btn-primary">
                                        <span class="glyphicon glyphicon-search"></span> Filtrar
                                      </button>
                                    </form>

                            </div>
                        </div>
                        {% if publicly_available_jobs|length <= 0 %}
                            <strong>Nenhuma vaga encontrada...</strong>
                        {% endif %}
                    </div>
                </div>
                {% for job in publicly_available_jobs %}
                <div class="row justify-content-center" style="margin-top:10px;">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                              <a href="/job/{{job.pk}}">
                                <h4 class="card-title">{{job.title}}</h4>
                              </a>
                                <h6 class="text-muted card-subtitle mb-2">Localização: {{job.workplace}}</h6>
                                <h6 class="text-muted card-subtitle mb-2">Postada: {{job.created_at|naturalday}}</h6>
                                <hr/>
                                {%for skill in job.skills.all%}
                                    <span class="badge badge-pill badge-primary">{{skill}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-3 d-none d-md-block"><a href="{% url 'job_view' job.pk %}"><button class="btn btn-primary" type="button" style="height:75px;width:100%;margin-top:25px;">Mais Detalhes</button></a></div>
                </div>
                {% endfor %}
                <nav style="margin-top:10px;">
                    <ul class="pagination">
                      {% for page in pages %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'index' %}?page={{page}}{% if 'search' in request.GET %}&search={{ request.GET.search }}{% endif %}">{{ page }}</a>
                        </li>
                      {% endfor %}
                    </ul>
                </nav>
            </div>
        </section>
    </main>
  {%endblock main%}
  {% block extra_scripts%}
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script type="text/javascript">
  $(document).ready(function() {
    $('#id_skills').select2();
  });
  </script>
  {%endblock%}

pyjobs/core/templates/job_details.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}
{{job.title}} no PyJobs
{% endblock %}
{%block main%}
    <main class="page faq-page">
        <section class="clean-block clean-faq dark">
            <div class="container">
                <div class="block-heading">
                    <h1 class="text-info">{{job.title}}</h1>
                    <p>Postada: {{job.created_at|naturalday}}</p>
                </div>
                <div class="block-content">
                  {% if job.application_link %}
                  <a href="{{job.application_link}}">
                  <button class="btn btn-primary" type="button">Ir para o site da Vaga</button>
                  </a>
                  {% else %}
                    {% if logged_in %}
                      {% if applied %}
                        <button class="btn btn-primary" type="button">Você já aplicou a esta vaga!</button>
                      {%else%}
                      <form action="." method="post">
                        {% csrf_token %}
                        <button class="btn btn-primary" type="submit">Candidate-se para esta vaga pelo PyJobs</button>
                      </form>
                      {% endif %}
                    {%else%}
                      <button class="btn btn-primary" type="button">Você precisa estar logado para se candidatar para esta vaga!</button>
                    {% endif %}
                  {% endif %}
                    <div class="faq-item">
                        <div class="answer">
                            {%for skill in job.skills.all%}
                                <span class="badge badge-pill badge-primary">{{skill}}</span>
                            {%endfor%}
                        </div>
                    </div>
                    <div class="faq-item">
                        <h4 class="question">Atributos da vaga:</h4>
                        <div class="answer">
                            <p>
                                <ul>
                                    <li>Empresa: {{job.company_name}}</li>
                                    <li>Faixa salarial: {{job.get_salary_range_display}}</li>
                                    <li>Estado: {{job.get_state_display}}</li>
                                    <li>Local da vaga: {{job.workplace}}</li>
                                    <li>Nível: {{job.get_job_level_display}}</li>
                                    <li>Aceita Remoto?: {% if job.remote %} Sim {%else%} N&atilde;o {%endif%}</li>
                                </ul>
                            </p>
                        </div>
                        <h4 class="question">Descrição da vaga</h4>
                        <div class="answer">
                          <p>
                            {{job.description|linebreaks}}
                          </p>
                        </div>
                    </div>
                    <div class="faq-item">
                        <h4 class="question">Requisitos</h4>
                        <div class="answer">
                          <p>
                            {{job.requirements|linebreaks}}
                          </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{%endblock%}

pyjobs/core/templates/pythonistas-area-info-change.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{%block main%}
    <main class="page contact-us-page">
        <section class="clean-block clean-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-info">Área do Pythonista</h2>
                </div>
                <form action="." method="post">
                  <p>{{ message }}</p>
                  {% csrf_token %}
                  {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                  {% endfor %}
                  {% for field in form.visible_fields %}
                  {% if field.html_name != "skills" %}
                  <div class="form-group" style="margin-top:5px">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          {{ field.label_tag }}
                        </span>
                      </div>
                      {% if field.errors %}
                      {% render_field field class="form-control is-invalid" %}
                      {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                      {% endfor %}
                      {%else%}
                        {% render_field field class="form-control" %}
                      {%endif%}
                      <div class="input-group-append">
                        {% if field.help_text %}
                          <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                  </div>
                  {%else%}
                  <div class="form-group">
                      <br>
                      <label for="exampleInputEmail1">Skills</label>
                      <small class="form-text text-muted">Preencha com as skills que você se encontra apto a executar ou que possua conhecimento</small>
                      <br>
                      {% render_field field  %}
                    </div>
                  {%endif%}
                  {%endfor%}
                    <div class="form-group">
                      <button class="btn btn-primary btn-block" type="submit">Atualize suas informações</button>
                    </div>
                </form>
            </div>
        </section>
    </main>
{%endblock%}
{% block extra_scripts%}
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#id_skills').select2();
});
</script>
{%endblock%}